config/routes.rb
SongPunch::Application.routes.draw do

 
resources :pages
resources :concerts
resources :users, only: [:new, :create]
resources :sessions, only: [:new, :create]

root to: "home#index"

get "pages/about"

  

end

app/models/concert.rb
class Concert < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :subscription


	validates :subscription, 
	presence: true

	validates :amount
	presence: true
	numericality: { only_integer: true }

	validates :paid_at
	









end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :user
  belongs_to :concert
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user

  validates :user,
  presence: true

  validates :start_date,
  presence: true

  validates :last_payment_date, 
  presence: true



	def change!
		v= stripe.charge(800), self.user.card.token ...
	end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :first_name, 
		presence: true

	validates :last_name, 
		presence: true

	validates :email,
		presence: true

	validates :password, 
		presence: true

	validates :password, 
	length: { in: 6..20 }, on: :create

	validates :password_confirmation, 
		presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 

  protect_from_forgery with: :exception
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

	def index
		# @concerts = Concert.all
		city = params[:city]
		@concerts = Concert.where(city: city)
	end

	def new
		@concerts = Concert.new
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def top20
  	@concert = Concert.find(params[:id])
  end

  def about
  	
  end

  def contact
  end

  def show
    @concert = Concert.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by(email: params[:email])

  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to concerts_path
  	else 
  		render :new
  	end
  end

end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	  @user = User.new
	end

	def create
 	  @user = User.new(user_params)
	
		if @user.save 
			session[:user_id] = @user.id # auto-log-in
			redirect_to concerts_path notice: "#{@user.first_name} was submitted successfully!"
			print "Signed In"
		else
		  render :new
		end
	end	

	protected 

	def user_params
		params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concerts/index.html.erb
<h1>List of Concerts in <%= params[:city] %> </h1>

<div class="concert-list">
	<% if @concerts.any? %>
		<p class="info">
			Check it out brah, these are the concerts in your hood:
		</p>
		<ul>
			<% @concerts.each do |c| %>
				<li>
					<%= link_to c.title, concert_path(c) %>
				</li>
			<% end %> 
		</ul>
	<% else %> 
		<p class="error">
			No concerts, because... well <br/>
			your city sucks brah!

			<br/><br/>
			
			<%= link_to 'Try again!', :back %>
		</p>
	<% end %>
</ul>

app/views/concerts/show.html.erb
<%= link_to "Back", concert_path %>


<h2><%= @concert.title.downcase %> (<%= link_to "edit", edit_concert_path(@concert) %>)</h2>
<p><%= @concert.date %></p>
<small>- <%= @concert.city %></small>

app/views/home/index.html.erb
<h1>Song Punch</h1>

<div class="concert-search">
	<%= form_tag '/concerts', method: :get do %> 
		<%= text_field_tag 'city' %>
		<%= submit_tag "Submit", class: "btn btn-default" %>
	<% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  
  <nav>
      <p><%= link_to "Sign In/Up", '/users/new' %></p>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SongPunch</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<% flash.each do |key, value| %>
    <%= content_tag(:div, value) %> 
<% end %>

<%= yield %>
<%= render "layouts/footer" %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Song Punch</h1>
<p id="about">Song Punch is the first-ever site on the interweb that shows the user the tour dates of bands coming to their city!</p>
<p id="about">It's super exciting! Thank you for visiting!</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Jeff McLean</p>
<p>Vancouver, BC</p>
<p>Planet Earth</p>

app/views/pages/top20.html.erb
<h1> Top 20 </h1>

<%= link_to "Back", concert_path %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		
	</title>
</head>
<body>
  <h1>User Index Pg</h1>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign In/Up</h1>
<div class= "sign-up">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br> 
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "first_name", "First Name" %><br>
    <%= f.text_field "first_name" %>
  </div>
  <div>
    <%= f.label "last_name", "Last Name" %><br>
    <%= f.text_field "last_name" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_Confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		
	</title>
</head>
<body>
	<h1>users page</h1>
</body>
</html>

app/views/users/users.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>
		
	</title>
</head>
<body>
	<h1>users page</h1>
</body>
</html>